app = 'capacity-tool'
primary_region = 'ams'

[build]

[env]
  PORT = '3000'
  DB_PATH = '/data/data.db'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'capacity_data'
  destination = '/data'
